name: Build and deploy ASP.Net Core app to Azure Web App - leadher-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_PATH: './LeadHer backEnd/BlogApp_BackEnd.csproj'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore "${{ env.PROJECT_PATH }}"

      - name: Build
        run: dotnet build "${{ env.PROJECT_PATH }}" --configuration Release --no-restore

      - name: Publish
        run: dotnet publish "${{ env.PROJECT_PATH }}" --configuration Release --no-restore --output "${{ github.workspace }}/publish"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'leadher-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7CDF1500D4D24A189140CF6A2008A528 }}
          package: publish